### ISSUE TITLE
J011376 is C3 not C4

### ISSUE THREAD

**Issue by rptb1** [minlexx/whdbx_web#41]
I have scanned all the signatures in J011376 and they are all class 3 according to https://wiki.eveuniversity.org/Wormhole_sites#Class_3 .  Furthermore there are unguarded data and relic sites.  I believe this is a C3 shattered system, but https://eve-wh.space/J011376 says C4.

**Comment by minlexx** [comment]
According to statics it should be C4, because both  X877 and H900 are outgoing static **from C4 system** (to C4 and C5 respectively).

But often shattered systems have mixed set of signatures from adjacent classes, like for example shattered C5's have signatures from C6. What exactly made you think that J011376 is C3?

**Comment by minlexx** [comment]
Anoik.is and ellatha say this is C4, so.. probably you're wrong
